a=int(input("enter the number of 10 rupes coin:"))
b=int(input("enter the number of 5 rupes coin:"))
c=int(input("enter the number of 2 rupes coine:"))
d=int(input("enter the number of 1 rupes coine:"))
total_money= (10*a)+(5*b)+(2*c)+(1*d)
print("Total money in piggi bank: ",total_money,"rupee")